### ISSUE TITLE
Breaks code using "aligned"

### ISSUE THREAD

**Issue by maeher** [arnomi/cryptocode#3]
The following document will not compile

```
\documentclass{article}
\usepackage{cryptocode}
\usepackage{amsmath}
\begin{document}
\begin{align*}
\begin{aligned}&\end{aligned}
\end{align*}
\end{document}
```

however, it compiles fine if the cryptocode package is not loaded as in

```
\documentclass{article}
%\usepackage{cryptocode}
\usepackage{amsmath}
\begin{document}
\begin{align*}
\begin{aligned}&\end{aligned}
\end{align*}
\end{document}
```

The issue is also fixed by adding a single whitespace as in

```
\documentclass{article}
\usepackage{cryptocode}
\usepackage{amsmath}
\begin{document}
\begin{align*}
\begin{aligned} &\end{aligned}
\end{align*}
\end{document}
```

I cannot really figure out how the error occurs but clearly this is an unintended side effect of something.

**Comment by arnomi** [comment]
I didn't check this, but could you try not loading amsmath? As cryptocode is using (and loading amsmath) this might be an artifact of loading it twice.

**Comment by maeher** [comment]
No, this doesn't change anything.

```
\documentclass{article}
\usepackage{cryptocode}
%\usepackage{amsmath}
\begin{document}
\begin{align*}
\begin{aligned}&\end{aligned}
\end{align*}
\end{document}
```

behaves identically, except that the test *without* cryptocode no longer works, because align* and aligned are not defined.

**Comment by arnomi** [comment]
Interesting. I'll try to look into this. Will probably be a few days though before I get to this.

**Comment by arnomi** [comment]
I finally got to looking at this. Sorry for the long wait. The culprit is, in fact, the `mathtools` package which cryptocode depends upon. The issue is reproducible using

```
\documentclass{article}

\usepackage{amsmath}
\usepackage{mathtools}

\begin{document}

\begin{align*}
\begin{aligned}&\end{aligned}
\end{align*}

\end{document}
```

At this point I think there is not much I can do. I think your best bet to better understand the issue is to post a question on [https://tex.stackexchange.com/](https://tex.stackexchange.com/). I did a quick search there but didn't find any pointers regarding the issue. If you do post a question, it would be great if you could reference it here.
